name: "Check Content"
description: "AI-assisted action to close spammy, off-topic or otherwise unwanted issues."
author: "machiecodes"

branding:
  icon: "trash"
  color: "white"

inputs:
  gemini-model:
    description: The Gemini model to use.
    required: true
  retry-attempts:
    description: The number of times to retry the AI request.
    required: true
    default: "5"
  project-context:
    description: Provide project-specific context for the AI.
    required: false
  close-label:
    description: The label to apply when closing an issue.
    required: false

runs:
  using: "node24"
  main: "dist/index.js"